name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check_context:
    name: Check context
    runs-on: ubuntu-latest
    outputs:
      app_context_1: ${{ steps.check.outputs.app_context_1 }}
      app_context_2: ${{ steps.check.outputs.app_context_2 }} 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Check context
        id: check
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file == "src/app1"* ]]; then
              echo "This modified file is in the 'app1' folder."
              echo "::set-output name=app_context_1::true"
              break
            fi
            if [[ $file == "src/app2"* ]]; then
              echo "This modified file is in the 'app2' folder."
              echo "::set-output name=app_context_2::true"
              break
            fi
          done < files.txt
     
  build:
    name: Build
    needs: [check_context]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze App 1
        if: needs.check_context.outputs.app_context_1 == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
        working-directory: src/app1
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=$SONAR_HOST
      - name: Build and analyze App 2
        if: needs.check_context.outputs.app_context_2 == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
        working-directory: src/app2
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=$SONAR_HOST
